/*
 * MIT License
 * 
 * Copyright (c) 2022 Kara
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

typedef struct error_code {
	int code;
	const char *msg;
} error_code;

error_code ssl_codes[] = {
	{ SSL_ERROR_NONE, "SSL_ERROR_NONE" },
	{ SSL_ERROR_ZERO_RETURN, "SSL_ERROR_ZERO_RETURN" },
	{ SSL_ERROR_WANT_READ, "SSL_ERROR_WANT_READ" },
	{ SSL_ERROR_WANT_WRITE, "SSL_ERROR_WANT_WRITE" },
	{ SSL_ERROR_WANT_CONNECT, "SSL_ERROR_WANT_CONNECT" },
	{ SSL_ERROR_WANT_ACCEPT, "SSL_ERROR_WANT_ACCEPT" },
	{ SSL_ERROR_WANT_X509_LOOKUP, "SSL_ERROR_WANT_X509_LOOKUP" },
	{ SSL_ERROR_WANT_ASYNC, "SSL_ERROR_WANT_ASYNC" },
	{ SSL_ERROR_WANT_ASYNC_JOB, "SSL_ERROR_WANT_ASYNC_JOB" },
	{ SSL_ERROR_WANT_CLIENT_HELLO_CB, "SSL_ERROR_WANT_CLIENT_HELLO_CB" },
	{ SSL_ERROR_SYSCALL, "SSL_ERROR_SYSCALL" },
	{ SSL_ERROR_SSL, "SSL_ERROR_SSL" }
};

#define SSL_CODES_SIZE (sizeof(ssl_codes) / sizeof(error_code))

error_code verify_codes[] = {
	{ X509_V_OK, "X509_V_OK" },
	{ X509_V_ERR_UNSPECIFIED, "X509_V_ERR_UNSPECIFIED" },
	{ X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT,
	  "X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT" },
	{ X509_V_ERR_UNABLE_TO_GET_CRL, "X509_V_ERR_UNABLE_TO_GET_CRL" },
	{ X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE,
	  "X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE" },
	{ X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE,
	  "X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE" },
	{ X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY,
	  "X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY" },
	{ X509_V_ERR_CERT_SIGNATURE_FAILURE,
	  "X509_V_ERR_CERT_SIGNATURE_FAILURE" },
	{ X509_V_ERR_CRL_SIGNATURE_FAILURE,
	  "X509_V_ERR_CRL_SIGNATURE_FAILURE" },
	{ X509_V_ERR_CERT_NOT_YET_VALID, "X509_V_ERR_CERT_NOT_YET_VALID" },
	{ X509_V_ERR_CERT_HAS_EXPIRED, "X509_V_ERR_CERT_HAS_EXPIRED" },
	{ X509_V_ERR_CRL_NOT_YET_VALID, "X509_V_ERR_CRL_NOT_YET_VALID" },
	{ X509_V_ERR_CRL_HAS_EXPIRED, "X509_V_ERR_CRL_HAS_EXPIRED" },
	{ X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD,
	  "X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD" },
	{ X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD,
	  "X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD" },
	{ X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD,
	  "X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD" },
	{ X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD,
	  "X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD" },
	{ X509_V_ERR_OUT_OF_MEM, "X509_V_ERR_OUT_OF_MEM" },
	{ X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT,
	  "X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT" },
	{ X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN,
	  "X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN" },
	{ X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY,
	  "X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY" },
	{ X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE,
	  "X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE" },
	{ X509_V_ERR_CERT_CHAIN_TOO_LONG, "X509_V_ERR_CERT_CHAIN_TOO_LONG" },
	{ X509_V_ERR_CERT_REVOKED, "X509_V_ERR_CERT_REVOKED" },
	{ X509_V_ERR_INVALID_CA, "X509_V_ERR_INVALID_CA" },
	{ X509_V_ERR_PATH_LENGTH_EXCEEDED, "X509_V_ERR_PATH_LENGTH_EXCEEDED" },
	{ X509_V_ERR_INVALID_PURPOSE, "X509_V_ERR_INVALID_PURPOSE" },
	{ X509_V_ERR_CERT_UNTRUSTED, "X509_V_ERR_CERT_UNTRUSTED" },
	{ X509_V_ERR_CERT_REJECTED, "X509_V_ERR_CERT_REJECTED" },
	{ X509_V_ERR_SUBJECT_ISSUER_MISMATCH,
	  "X509_V_ERR_SUBJECT_ISSUER_MISMATCH" },
	{ X509_V_ERR_AKID_SKID_MISMATCH, "X509_V_ERR_AKID_SKID_MISMATCH" },
	{ X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH,
	  "X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH" },
	{ X509_V_ERR_KEYUSAGE_NO_CERTSIGN, "X509_V_ERR_KEYUSAGE_NO_CERTSIGN" },
	{ X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER,
	  "X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER" },
	{ X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION,
	  "X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION" },
	{ X509_V_ERR_KEYUSAGE_NO_CRL_SIGN, "X509_V_ERR_KEYUSAGE_NO_CRL_SIGN" },
	{ X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION,
	  "X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION" },
	{ X509_V_ERR_INVALID_NON_CA, "X509_V_ERR_INVALID_NON_CA" },
	{ X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED,
	  "X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED" },
	{ X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION,
	  "X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION" },
	{ X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE,
	  "X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE" },
	{ X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED,
	  "X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED" },
	{ X509_V_ERR_INVALID_EXTENSION, "X509_V_ERR_INVALID_EXTENSION" },
	{ X509_V_ERR_INVALID_POLICY_EXTENSION,
	  "X509_V_ERR_INVALID_POLICY_EXTENSION" },
	{ X509_V_ERR_NO_EXPLICIT_POLICY, "X509_V_ERR_NO_EXPLICIT_POLICY" },
	{ X509_V_ERR_DIFFERENT_CRL_SCOPE, "X509_V_ERR_DIFFERENT_CRL_SCOPE" },
	{ X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE,
	  "X509_V_ERR_UNSUPPORTED_EXTENSION_FEATURE" },
	{ X509_V_ERR_UNNESTED_RESOURCE, "X509_V_ERR_UNNESTED_RESOURCE" },
	{ X509_V_ERR_PERMITTED_VIOLATION, "X509_V_ERR_PERMITTED_VIOLATION" },
	{ X509_V_ERR_EXCLUDED_VIOLATION, "X509_V_ERR_EXCLUDED_VIOLATION" },
	{ X509_V_ERR_SUBTREE_MINMAX, "X509_V_ERR_SUBTREE_MINMAX" },
	{ X509_V_ERR_APPLICATION_VERIFICATION,
	  "X509_V_ERR_APPLICATION_VERIFICATION" },
	{ X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE,
	  "X509_V_ERR_UNSUPPORTED_CONSTRAINT_TYPE" },
	{ X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX,
	  "X509_V_ERR_UNSUPPORTED_CONSTRAINT_SYNTAX" },
	{ X509_V_ERR_UNSUPPORTED_NAME_SYNTAX,
	  "X509_V_ERR_UNSUPPORTED_NAME_SYNTAX" },
	{ X509_V_ERR_CRL_PATH_VALIDATION_ERROR,
	  "X509_V_ERR_CRL_PATH_VALIDATION_ERROR" },
	{ X509_V_ERR_PATH_LOOP, "X509_V_ERR_PATH_LOOP" },
	{ X509_V_ERR_SUITE_B_INVALID_VERSION,
	  "X509_V_ERR_SUITE_B_INVALID_VERSION" },
	{ X509_V_ERR_SUITE_B_INVALID_ALGORITHM,
	  "X509_V_ERR_SUITE_B_INVALID_ALGORITHM" },
	{ X509_V_ERR_SUITE_B_INVALID_CURVE,
	  "X509_V_ERR_SUITE_B_INVALID_CURVE" },
	{ X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM,
	  "X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM" },
	{ X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED,
	  "X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED" },
	{ X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256,
	  "X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256" },
	{ X509_V_ERR_HOSTNAME_MISMATCH, "X509_V_ERR_HOSTNAME_MISMATCH" },
	{ X509_V_ERR_EMAIL_MISMATCH, "X509_V_ERR_EMAIL_MISMATCH" },
	{ X509_V_ERR_IP_ADDRESS_MISMATCH, "X509_V_ERR_IP_ADDRESS_MISMATCH" },
	{ X509_V_ERR_DANE_NO_MATCH, "X509_V_ERR_DANE_NO_MATCH" },
	{ X509_V_ERR_EE_KEY_TOO_SMALL, "X509_V_ERR_EE_KEY_TOO_SMALL" },
	{ X509_V_ERR_CA_KEY_TOO_SMALL, "X509_ERR_CA_KEY_TOO_SMALL" },
	{ X509_V_ERR_CA_MD_TOO_WEAK, "X509_ERR_CA_MD_TOO_WEAK" },
	{ X509_V_ERR_INVALID_CALL, "X509_V_ERR_INVALID_CALL" },
	{ X509_V_ERR_STORE_LOOKUP, "X509_V_ERR_STORE_LOOKUP" },
	{ X509_V_ERR_NO_VALID_SCTS, "X509_V_ERR_NO_VALID_SCTS" },
	{ X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION,
	  "X509_V_ERR_PROXY_SUBJECT_NAME_VIOLATION" },
	{ X509_V_ERR_OCSP_VERIFY_NEEDED, "X509_V_ERR_OCSP_VERIFY_NEEDED" },
	{ X509_V_ERR_OCSP_VERIFY_FAILED, "X509_V_ERR_OCSP_VERIFY_FAILED" },
	{ X509_V_ERR_OCSP_CERT_UNKNOWN, "X509_V_ERR_OCSP_CERT_UNKNOWN" }
};

#define VERIFY_CODES_SIZE (sizeof(verify_codes) / sizeof(error_code))

const char *krossock_strerror(error_code *codes, size_t size, int code)
{
	size_t i = 0;
	for (; i < size; i++) {
		if (codes[i].code == code)
			return codes[i].msg;
	}

	return "UNKNOWN";
}

void ssl_helper_print_certificate(X509 *cert)
{
	char subj[SSL_HELPER_BUFFER_SIZE + 1];
	char issuer[SSL_HELPER_BUFFER_SIZE + 1];
	X509_NAME_oneline(X509_get_subject_name(cert), subj,
			  SSL_HELPER_BUFFER_SIZE);
	X509_NAME_oneline(X509_get_issuer_name(cert), issuer,
			  SSL_HELPER_BUFFER_SIZE);
	printf("certificate: %s\n", subj);
	printf("\tissuer: %s\n\n", issuer);
	fflush(stdout);
}
